name: graphmix
channels:
  - conda-forge
dependencies:
  - python=3.9
  - metis
  - pybind11
  - cmake
  - tqdm
  - numpy
  - pyyaml
  - libprotobuf
  - zeromq
  - pip
# the following are just for running tests and examples
  - pytorch
  - tensorflow
