env:
  GRAPHMIX_ROOT_URI : 127.0.0.1
  GRAPHMIX_ROOT_PORT : 8889
  GRAPHMIX_NUM_WORKER : 4
  MASTER_ADDR : 127.0.0.1
  MASTER_PORT : 8888
launch:
  worker : 4
  server : 4
  scheduler : true
  data : ../data/Cora
